all:
  children:
    rac_primary:
      hosts:
        rac-node1.company.local:
          ansible_host: 192.168.30.11
          public_if: ens192
          private_if: ens224
          management_if: ens256
          public_ip: 192.168.10.11
          private_ip: 192.168.20.11
          management_ip: 192.168.30.11
          public_prefix: 24
          private_prefix: 24
          management_prefix: 24
          public_gw: 192.168.10.1
        rac-node2.company.local:
          ansible_host: 192.168.30.12
          public_if: ens192
          private_if: ens224
          management_if: ens256
          public_ip: 192.168.10.12
          private_ip: 192.168.20.12
          management_ip: 192.168.30.12
          public_prefix: 24
          private_prefix: 24
          management_prefix: 24
          public_gw: 192.168.10.1
