all:
  children:
    rac_primary:
      hosts:
        rac-node1.company.local:
          ansible_host: 192.168.30.11
          short_hostname: rac-node1
          vip_hostname: rac-node1-vip.company.local
          private_hostname: rac-node1-priv.company.local
          oracle_instance_name: pridb1
          grid_oracle_sid: +ASM1
          public_if: ens192
          private_if: ens224
          management_if: ens256
          public_ip: 192.168.10.11
          private_ip: 192.168.20.11
          management_ip: 192.168.30.11
          public_prefix: 24
          private_prefix: 24
          management_prefix: 24
          public_gw: 192.168.10.1
        rac-node2.company.local:
          ansible_host: 192.168.30.12
          short_hostname: rac-node2
          vip_hostname: rac-node2-vip.company.local
          private_hostname: rac-node2-priv.company.local
          oracle_instance_name: pridb2
          grid_oracle_sid: +ASM2
          public_if: ens192
          private_if: ens224
          management_if: ens256
          public_ip: 192.168.10.12
          private_ip: 192.168.20.12
          management_ip: 192.168.30.12
          public_prefix: 24
          private_prefix: 24
          management_prefix: 24
          public_gw: 192.168.10.1

