ansible_user: ansible
ansible_become: true
dns_servers:
  - 192.168.10.53
  - 192.168.10.54
oracle_groups:
  - { name: "oinstall", gid: 1001 }
  - { name: "dba", gid: 1002 }
  - { name: "asmadmin", gid: 1003 }
  - { name: "asmdba", gid: 1004 }
  - { name: "asmoper", gid: 1005 }
oracle_users:
  - { name: "grid", uid: 1101, groups: "asmadmin,asmdba,asmoper,dba" }
  - { name: "oracle", uid: 1102, groups: "dba,asmdba" }
oracle_directories:
  - /u01/app
  - /u01/app/grid
  - /u01/app/oracle
  - /u01/app/21c/grid
  - /u01/app/product/db21c
  - /u01/app/oraInventory
  - /u01/stage
oracle_required_packages:
  - chrony
  - unzip
  - kmod
  - libaio
  - libnsl
  - python3
scan_name: scan-db.company.local
db_service_name: db.company.local
primary_scan_name: scan-db.company.local
standby_scan_name: scan-standby.company.local
listener_port: 1521
scan_port: 1521
cluster_name: prod-rac
oracle_base: /u01/app/oracle
grid_base: /u01/app/grid
grid_home: /u01/app/21c/grid
db_home: /u01/app/product/db21c
oracle_inventory: /u01/app/oraInventory
automation_response_dir: /u01/app/automation
oracle_grid_stage_zip: /u01/stage/LINUX.X64_213000_grid_home.zip
oracle_db_stage_zip: /u01/stage/LINUX.X64_213000_db_home.zip
oracle_db_edition: EE
oracle_asm_password: ChangeMe_Asm123
oracle_sys_password: ChangeMe_Db123
asm_diskstring: /dev/oracleasm/disks/*
asm_ocr_disks:
  - /dev/oracleasm/disks/OCR1
  - /dev/oracleasm/disks/OCR2
  - /dev/oracleasm/disks/OCR3
asm_diskgroups:
  - name: DATA
    disk_list:
      - /dev/oracleasm/disks/DATA01
    redundancy: EXTERNAL
    au_size: 4
  - name: FRA
    disk_list:
      - /dev/oracleasm/disks/FRA01
    redundancy: EXTERNAL
    au_size: 4
rac_db_name: pridb
rac_db_sid_prefix: pridb
rac_pdb_name: pridbpdb1
rac_db_processes: 1280
rac_db_sga_target_mb: 71680
rac_db_pga_target_mb: 20480
rac_db_total_memory_mb: 92160
rac_db_fra_size_mb: 4194304
redo_log_size_mb: 1024
dbexpress_port: 5500
primary_db_unique_name: pridb
standby_db_unique_name: drdb
primary_dg_service_name: pridb_dg
standby_dg_service_name: drdb_dg
primary_dg_connect_identifier: pridb_sync
standby_dg_connect_identifier: drdb_sync
dg_configuration_name: dg_config
standby_redo_logs:
  - { thread: 1, group: 11, size_mb: 1024 }
  - { thread: 1, group: 12, size_mb: 1024 }
  - { thread: 1, group: 13, size_mb: 1024 }
  - { thread: 2, group: 21, size_mb: 1024 }
  - { thread: 2, group: 22, size_mb: 1024 }
  - { thread: 2, group: 23, size_mb: 1024 }

