all:
  children:
    rac_dr:
      hosts:
        rac-node3.company.local:
          ansible_host: 192.168.130.11
          short_hostname: rac-node3
          vip_hostname: rac-node3-vip.company.local
          private_hostname: rac-node3-priv.company.local
          oracle_instance_name: drdb1
          grid_oracle_sid: +ASM1
          public_if: ens192
          private_if: ens224
          management_if: ens256
          public_ip: 192.168.110.11
          private_ip: 192.168.120.11
          management_ip: 192.168.130.11
          public_prefix: 24
          private_prefix: 24
          management_prefix: 24
          public_gw: 192.168.110.1
        rac-node4.company.local:
          ansible_host: 192.168.130.12
          short_hostname: rac-node4
          vip_hostname: rac-node4-vip.company.local
          private_hostname: rac-node4-priv.company.local
          oracle_instance_name: drdb2
          grid_oracle_sid: +ASM2
          public_if: ens192
          private_if: ens224
          management_if: ens256
          public_ip: 192.168.110.12
          private_ip: 192.168.120.12
          management_ip: 192.168.130.12
          public_prefix: 24
          private_prefix: 24
          management_prefix: 24
          public_gw: 192.168.110.1

